intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libimgui%lib{imgui}

# Public headers.
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{imgui-platform-osx}: libul{imgui-platform-osx}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
# This backend is macOS-only (Objective-C++); exclude the source on other
# platforms so the library builds (empty) instead of failing to compile.
#
libul{imgui-platform-osx}: {hxx cxx}{**} $impl_libs $intf_libs
libul{imgui-platform-osx}: mm{imgui_impl_osx}: include = ($cxx.target.class == 'macos')

# __bridge_retained in imgui_impl_osx.mm retains only under ARC.
# The other two flags silence upstream warnings that are not our bug:
# a GNU ?: with the middle operand omitted, and a deprecated AppKit call.
#
if ($cxx.target.class == 'macos')
{
  cxx.coptions += -fobjc-arc -Wno-gnu-conditional-omitted-operand \
                  -Wno-deprecated-declarations
  cxx.libs += -framework Cocoa -framework Carbon -framework GameController
}

libs{imgui-platform-osx}: def{imgui-platform-osx}: include = ($cxx.target.system == 'win32-msvc')
def{imgui-platform-osx}: libul{imgui-platform-osx}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" \
                "-I$out_pfx_inc/backends" "-I$src_pfx_inc/backends"

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{imgui-platform-osx}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc" \
                        "-I$out_pfx_inc/backends" "-I$src_pfx_inc/backends"
  cxx.export.libs = $intf_libs
  cxx.pkgconfig.include = include/ include/backends/
}

if ($cxx.target.class == 'macos')
  lib{imgui-platform-osx}: cxx.export.libs += -framework Cocoa -framework Carbon -framework GameController

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{imgui-platform-osx}: bin.lib.version = "-$version.project_id"
else
  lib{imgui-platform-osx}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
hxx{*}: install = false
