libs =
import libs += libimgui-platform-glfw%lib{imgui-platform-glfw} \
               libimgui-render-metal%lib{imgui-render-metal} \
               glfw%lib{glfw}

exe{example-metal}: {hxx mm}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
