pub_hdrs = hxx{**}

./: $pub_hdrs

# Install recreating subdirectories.
#
hxx{*}:
{
  install         = include/
  install.subdirs = true
}

# Only the enabled FreeType build installs this header.
#
if! $config.libimgui.freetype
  imgui/misc/freetype/hxx{imgui_freetype}@imgui/misc/freetype/: install = false
