# This whole package is Windows-only (see manifest).
#
./: {*/ -build/ -opengl3/ -vulkan/ -directx12/} doc{README.md PACKAGE-README.md CHANGELOG.txt} legal{LICENSE.txt} manifest

./: {opengl3/ vulkan/ directx12/}: include = ($cxx.target.class == 'windows')

# The examples are for trying out the backends from the build directory,
# not for installing.
#
exe{*}: install = false
