# This whole package is macOS-only (see manifest).
#
./: {*/ -build/ -metal/} doc{README.md PACKAGE-README.md CHANGELOG.txt} legal{LICENSE.txt} manifest

./: metal/: include = ($cxx.target.class == 'macos')

# The examples are for trying out the backends from the build directory,
# not for installing.
#
exe{*}: install = false
