intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs += libimgui%lib{imgui}

# Public headers.
#
pub = [dir_path] ../include/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{imgui-platform-win32}: libul{imgui-platform-win32}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
# This backend is Windows-only; exclude the source on other platforms so
# the library builds (empty) instead of failing to compile.
#
libul{imgui-platform-win32}: {hxx cxx}{** -imgui_impl_win32} $impl_libs $intf_libs
libul{imgui-platform-win32}: cxx{imgui_impl_win32}: include = ($cxx.target.class == 'windows')

if ($cxx.target.class == 'windows')
{
  if ($cxx.target.system == 'mingw32')
    cxx.libs += -lgdi32 -ldwmapi
  else
    cxx.libs += gdi32.lib dwmapi.lib
}

libs{imgui-platform-win32}: def{imgui-platform-win32}: include = ($cxx.target.system == 'win32-msvc')
def{imgui-platform-win32}: libul{imgui-platform-win32}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{imgui-platform-win32}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{imgui-platform-win32}: bin.lib.version = "-$version.project_id"
else
  lib{imgui-platform-win32}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
hxx{*}: install = false
